version: '3.6'
services:
  postgres:
    ports:
      - "5432:5432"
  graphql-engine:
    ports:
      - "8080:8080"
  hasura-auth:
    ports:
      - "4000:4000"
#    command: yarn start:dev
    volumes:
      - /app/node_modules
    environment:
      ALLOW_EMPTY_ORGANIZATION: 'false'